// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Unakin
{
    internal sealed partial class Vsix
    {
        public const string Id = "VisualUnakinStudio2019.4854bc98-735d-4622-a0cf-30454b50aa0f";
        public const string Name = "Visual Unakin Studio 2019";
        public const string Description = @"Add Unakin functionalities directly on Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "2.2.3";
        public const string Author = "Unakin";
        public const string Tags = "Unakin, Visual Studio";
    }
}
