// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Unakin
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string UnakinString = "1e5e84f8-48b1-4c7e-8634-13a1fc0bd1ba";
        public static Guid Unakin = new Guid(UnakinString);

        public const string guidSemanticSearchToolPackageCmdSetString = "5e468798-3c94-40c3-8915-e86dffeef3da";
        public static Guid guidSemanticSearchToolPackageCmdSet = new Guid(guidSemanticSearchToolPackageCmdSetString);

        public const string guidUnakinPackageCmdSetString = "3ff86b45-d8b7-4978-9a3e-069edae059bf";
        public static Guid guidUnakinPackageCmdSet = new Guid(guidUnakinPackageCmdSetString);

        public const string UnakinCompleteIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eea";
        public static Guid UnakinCompleteIcon = new Guid(UnakinCompleteIconString);

        public const string UnakinAddTestsIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eeb";
        public static Guid UnakinAddTestsIcon = new Guid(UnakinAddTestsIconString);

        public const string UnakinFindBugsIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eec";
        public static Guid UnakinFindBugsIcon = new Guid(UnakinFindBugsIconString);

        public const string UnakinOptimizeIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eed";
        public static Guid UnakinOptimizeIcon = new Guid(UnakinOptimizeIconString);

        public const string UnakinOptimizeDiffViewIconString = "30e42718-2334-493f-9f85-db3b0f01f364";
        public static Guid UnakinOptimizeDiffViewIcon = new Guid(UnakinOptimizeDiffViewIconString);

        public const string UnakinExplainIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eee";
        public static Guid UnakinExplainIcon = new Guid(UnakinExplainIconString);

        public const string UnakinAddCommentsIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eef";
        public static Guid UnakinAddCommentsIcon = new Guid(UnakinAddCommentsIconString);

        public const string UnakinAddSummaryIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eaa";
        public static Guid UnakinAddSummaryIcon = new Guid(UnakinAddSummaryIconString);

        public const string UnakinaddSummaryForAllIconString = "2de8036f-824c-4b98-bf28-0805ccce17f4";
        public static Guid UnakinaddSummaryForAllIcon = new Guid(UnakinaddSummaryForAllIconString);

        public const string UnakinAskAnythingIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eba";
        public static Guid UnakinAskAnythingIcon = new Guid(UnakinAskAnythingIconString);

        public const string UnakinTranslateIconString = "ae75cd23-1146-4732-8ee1-7bfdacad3e17";
        public static Guid UnakinTranslateIcon = new Guid(UnakinTranslateIconString);

        public const string UnakinProjectSummaryIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eb1";
        public static Guid UnakinProjectSummaryIcon = new Guid(UnakinProjectSummaryIconString);

        public const string UnakinWebSearchIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eb2";
        public static Guid UnakinWebSearchIcon = new Guid(UnakinWebSearchIconString);

        public const string UnakinAutomatedTestingIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eb3";
        public static Guid UnakinAutomatedTestingIcon = new Guid(UnakinAutomatedTestingIconString);

        public const string UnakinCustomBeforeIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eca";
        public static Guid UnakinCustomBeforeIcon = new Guid(UnakinCustomBeforeIconString);

        public const string UnakinCustomAfterIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eda";
        public static Guid UnakinCustomAfterIcon = new Guid(UnakinCustomAfterIconString);

        public const string UnakinCustomReplaceIconString = "38a870f1-bed8-4322-b98b-11a53e51821c";
        public static Guid UnakinCustomReplaceIcon = new Guid(UnakinCustomReplaceIconString);

        public const string UnakinCancelIconString = "d346adf7-8df0-48de-b268-7149699b3cf8";
        public static Guid UnakinCancelIcon = new Guid(UnakinCancelIconString);

        public const string UnakinChatGPTIconString = "4c9af432-30b5-44cb-9a6e-3121c6dc7a49";
        public static Guid UnakinChatGPTIcon = new Guid(UnakinChatGPTIconString);

        public const string UnakinTurboIconString = "4c9af432-30b5-44cb-9a6e-3121c6dc7a50";
        public static Guid UnakinTurboIcon = new Guid(UnakinTurboIconString);

        public const string guidUnakinPackageCmdSet1String = "adbbafd6-daff-45bb-bfd7-3afa9f6e8987";
        public static Guid guidUnakinPackageCmdSet1 = new Guid(guidUnakinPackageCmdSet1String);

        public const string guidImagesString = "4f25ed68-89f2-4ed9-847c-45156c6c1f80";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GroupSubMenuUnakinMain = 0x1000;
        public const int MyGroupForCommands = 0x1001;
        public const int MySubMenu = 0x2000;
        public const int SemanticSearch = 0x0000;
        public const int Complete = 0x0001;
        public const int AddTests = 0x0100;
        public const int FindBugs = 0x0200;
        public const int Optimize = 0x0300;
        public const int OptimizeDiffView = 0x0301;
        public const int Explain = 0x0400;
        public const int AddComments = 0x0500;
        public const int AddSummary = 0x0600;
        public const int AddSummaryForAll = 0x0601;
        public const int AskAnything = 0x0700;
        public const int Translate = 0x0701;
        public const int ProjectSummary = 0x0702;
        public const int WebSearch = 0x0703;
        public const int AutomatedTesting = 0x0704;
        public const int ShortSearch = 0x0705;
        public const int CustomBefore = 0x0800;
        public const int CustomAfter = 0x0900;
        public const int CustomReplace = 0x0901;
        public const int Cancel = 0x0902;
        public const int Tutorial = 0x0903;
        public const int SementicSearchUnakinCommandId = 0x00FF;
        public const int cmdidTerminalWindowCommand = 0x0100;
        public const int cmdidTerminalWindowTurboCommand = 0x0101;
        public const int cmdidSementicSearchUnakinCommand = 0x0102;
        public const int completeIcon = 0x0001;
        public const int addTestsIcon = 0x0001;
        public const int findBugsIcon = 0x0001;
        public const int optimizeIcon = 0x0001;
        public const int optimizeDiffViewIcon = 0x0001;
        public const int explainIcon = 0x0001;
        public const int addCommentsIcon = 0x0001;
        public const int addSummaryIcon = 0x0001;
        public const int addSummaryForAllIcon = 0x0001;
        public const int askAnythingIcon = 0x0001;
        public const int translateIcon = 0x0001;
        public const int projectSummaryIcon = 0x0001;
        public const int webSearchIcon = 0x0001;
        public const int automatedTestingIcon = 0x0001;
        public const int customBeforeIcon = 0x0001;
        public const int customAfterIcon = 0x0001;
        public const int customReplaceIcon = 0x0001;
        public const int cancelIcon = 0x0001;
        public const int chatGPTIcon = 0x0001;
        public const int turboIcon = 0x0001;
        public const int MyMenuGroup = 0x1020;
        public const int cmdidUnitTesting = 0x270F;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}